# Generated by Django 5.0.6 on 2026-07-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_create_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawClaim',
            fields=[
                ('claim_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=50)),
                ('claim_status', models.CharField(max_length=30)),
                ('service_date_start', models.DateField()),
                ('service_date_end', models.DateField()),
                ('submitted_date', models.DateField()),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw"."raw_claims',
                'ordering': ['-service_date_start'],
            },
        ),
        migrations.CreateModel(
            name='RawDenialCode',
            fields=[
                ('denial_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('denial_reason', models.CharField(max_length=200)),
                ('denial_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raw"."raw_denial_codes',
            },
        ),
        migrations.CreateModel(
            name='RawDiagnosisCategory',
            fields=[
                ('diagnosis_category_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('diagnosis_category_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'raw"."raw_diagnosis_categories',
            },
        ),
        migrations.CreateModel(
            name='RawMember',
            fields=[
                ('member_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('subscriber_id', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('plan_type', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('term_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw"."raw_members',
                'ordering': ['member_id'],
            },
        ),
        migrations.CreateModel(
            name='RawPayer',
            fields=[
                ('payer_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=150)),
                ('payer_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw"."raw_payers',
                'ordering': ['payer_id'],
            },
        ),
        migrations.CreateModel(
            name='RawProcedureCategory',
            fields=[
                ('procedure_category_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('procedure_category_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'raw"."raw_procedure_categories',
            },
        ),
        migrations.CreateModel(
            name='RawProvider',
            fields=[
                ('provider_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('npi', models.CharField(max_length=20)),
                ('network_status', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw"."raw_providers',
                'ordering': ['provider_id'],
            },
        ),
        migrations.CreateModel(
            name='RawAdjustment',
            fields=[
                ('adjustment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(max_length=50)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_date', models.DateField()),
                ('reason_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawclaim')),
            ],
            options={
                'db_table': 'raw"."raw_adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.AddField(
            model_name='rawclaim',
            name='denial_code',
            field=models.ForeignKey(blank=True, db_column='denial_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.rawdenialcode'),
        ),
        migrations.AddField(
            model_name='rawclaim',
            name='diagnosis_category',
            field=models.ForeignKey(db_column='diagnosis_category_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.rawdiagnosiscategory'),
        ),
        migrations.CreateModel(
            name='RawEligibility',
            fields=[
                ('eligibility_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('plan_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawmember')),
            ],
            options={
                'db_table': 'raw"."raw_eligibility',
                'ordering': ['member_id', 'coverage_start'],
            },
        ),
        migrations.AddField(
            model_name='rawclaim',
            name='member',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawmember'),
        ),
        migrations.AddField(
            model_name='rawclaim',
            name='payer',
            field=models.ForeignKey(db_column='payer_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawpayer'),
        ),
        migrations.CreateModel(
            name='RawPayment',
            fields=[
                ('payment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawclaim')),
            ],
            options={
                'db_table': 'raw"."raw_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RawClaimServiceLine',
            fields=[
                ('service_line_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('service_date', models.DateField()),
                ('units', models.PositiveIntegerField(default=1)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawclaim')),
                ('procedure_category', models.ForeignKey(db_column='procedure_category_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.rawprocedurecategory')),
            ],
            options={
                'db_table': 'raw"."raw_claim_service_lines',
                'ordering': ['claim_id', 'line_number'],
            },
        ),
        migrations.AddField(
            model_name='rawclaim',
            name='provider',
            field=models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='warehouse.rawprovider'),
        ),
    ]
