# Generated by Django 5.0.6 on 2026-07-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_create_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=64)),
                ('user_role', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('CLAIM_DETAIL_VIEWED', 'Claim Detail Viewed'), ('MEMBER_DETAIL_VIEWED', 'Member Detail Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('ROLE_CHANGED', 'Role Changed'), ('ACCESS_DENIED', 'Access Denied'), ('DATA_QUALITY_CHECK_RUN', 'Data Quality Check Run'), ('DATA_QUALITY_CHECK_FAILED', 'Data Quality Check Failed'), ('RETENTION_JOB_RAN', 'Retention Job Ran')], max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('ERROR', 'Error')], default='SUCCESS', max_length=16)),
                ('ip_address_placeholder', models.CharField(default='0.0.0.0', max_length=32)),
            ],
            options={
                'db_table': 'audit"."audit_events',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('failed_count', models.IntegerField(default=0)),
                ('sample_record_key', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance"."data_quality_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
